1. Import numpy under the name np, and print its version.

In [2]:
import numpy as np 
print(np.__version__)

1.26.4


2. Create a null vector (an array of all zeros) of size 10.

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3.Create the same null vector of size 10, but this time make the 5th value equal to 1.

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4.Create a vector with values ranging from 10 to 49 (inclusive of 10, and you can decide whether 49 is included based on what function you use).

In [6]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5.Take the vector you just created and reverse it (so it goes from 49 down to 10).

In [10]:
arr = arr[::-1]
print(arr)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6.Create a 3x3 matrix with values ranging from 0 to 8.

In [15]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
