1. Import numpy under the name np, and print its version.

In [1]:
import numpy as np 
print(np.__version__)

1.26.4


2. Create a null vector (an array of all zeros) of size 10.

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3.Create the same null vector of size 10, but this time make the 5th value equal to 1.

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4.Create a vector with values ranging from 10 to 49 (inclusive of 10, and you can decide whether 49 is included based on what function you use).

In [6]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5.Take the vector you just created and reverse it (so it goes from 49 down to 10).

In [10]:
arr = arr[::-1]
print(arr)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6.Create a 3x3 matrix with values ranging from 0 to 8.

In [2]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7.find the indices of the non-zero elements in [1, 2, 0, 0, 4, 0].

In [4]:
arr = np.array([1,2,0,0,4,0])
print(arr[[0,1,4]]) # it gives us particular value of that indices, not indices itself

print(np.nonzero(arr)) # gives us indices of non zero value



[1 2 4]
(array([0, 1, 4], dtype=int64),)


8. Create a 3x3 identity matrix (1s on the diagonal, 0s everywhere else):

In [8]:
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. Create a 3x3x3 array filled with random values.

In [13]:
array = np.random.random((3,3,3))
print(array)
print(array.shape)
print(array.ndim)

[[[0.4859489  0.551745   0.6153703 ]
  [0.73039675 0.78502189 0.348687  ]
  [0.82155584 0.55820812 0.40507389]]

 [[0.39852971 0.72087634 0.55048676]
  [0.17887272 0.04291936 0.27350933]
  [0.04446404 0.63357463 0.35313059]]

 [[0.90262733 0.70428555 0.8508098 ]
  [0.92479206 0.44341177 0.21507382]
  [0.93647199 0.59941692 0.70737114]]]
(3, 3, 3)
3


10.Create a 10x10 array with random values, then find its minimum and maximum values.

In [16]:
array = np.random.random((10,10))
print(array)
print(array.shape) 
print(array.max())
print(array.min())

[[0.71002548 0.45293085 0.27617739 0.84817854 0.79096928 0.72341273
  0.31176264 0.76129708 0.68645067 0.58914682]
 [0.75574904 0.09046049 0.74983696 0.25036396 0.20657901 0.12102879
  0.82818639 0.999254   0.36462142 0.07120016]
 [0.3787666  0.81853278 0.87660213 0.89302735 0.73693602 0.7143503
  0.2905187  0.51564187 0.73513441 0.00372105]
 [0.47792786 0.27710593 0.61367589 0.25199809 0.89381248 0.85251746
  0.71480793 0.40985272 0.23607519 0.70860634]
 [0.65635619 0.52614484 0.24022523 0.6465151  0.79805603 0.42653817
  0.67515193 0.06185981 0.42652934 0.94445041]
 [0.12586687 0.65719946 0.3401822  0.99626189 0.48375946 0.48455446
  0.44953375 0.5993414  0.06680152 0.47290152]
 [0.48176583 0.2055654  0.30719669 0.55422012 0.06582105 0.59837861
  0.3522666  0.21766602 0.03457772 0.16542499]
 [0.65407592 0.26380733 0.86875451 0.06347686 0.58133399 0.53077234
  0.34154914 0.46146866 0.73487753 0.61880411]
 [0.39457593 0.28412879 0.94830176 0.39911856 0.60486781 0.17809752
  0.56099536 

11.Create a random vector of size 30 and find its mean value.

In [18]:
rand = np.random.random(30)
print(rand.mean())

0.5266654703332142


12.Create a 2D array with 1 on the border and 0 inside. For a 5x5 array it should look like this:

In [24]:
zeros_matrix = np.ones((5,5))
zeros_matrix[1:4,1:4] = 0
print(zeros_matrix)

border_matrix = np.ones((5, 5))
border_matrix[1:-1, 1:-1] = 0    # works for any size
print(border_matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


13.You have this 3x3 array of ones:

part of the line
arr: the array you want to pad.
pad_width=1: how many layers to add on every side (top, bottom, left, right). 1 adds one layer, 2 would add two.
mode='constant': fill the new layer with one fixed value.
constant_values=0: that fixed value. Here the border is filled with 0.

In [27]:
arr = np.zeros((5,5))
arr[1:-1,1:-1] = 1
print(arr)

arr = np.ones((3, 3))
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


14.predict the output

## np.nan and np.inf

**np.nan (Not a Number)**
- Represents a missing or undefined value (e.g. the result of `0/0`)
- Very common in Pandas when data has gaps
- `nan` is contagious: any arithmetic with `nan` gives `nan`
- `nan` is never equal to anything, not even itself

**np.inf (Infinity)**
- Represents a value larger than any number
- Any comparison involving `nan` is always False

**Floating-point precision**
- Computers store decimals approximately, so exact `==` comparisons on floats can fail
- To compare floats safely, use `np.isclose(a, b)` instead of `==`

## Floating-Point Precision

**The problem**
- Decimal arithmetic on computers is slightly inexact:
  - `0.1 + 0.2` gives `0.30000000000000004`, not `0.3`
  - `0.1 + 0.2 == 0.3` gives `False`

**Why it happens**
- Computers store numbers in binary
- Some decimals (like 0.1) can't be represented exactly in binary, just like 1/3 can't be written exactly in decimal (0.333...)
- The computer stores a very close approximation, and tiny errors add up in calculations

**The fix**
- Never use `==` to compare floats
- Use `np.isclose(a, b)`, which returns `True` if the two numbers are within a tiny tolerance
- Example: `np.isclose(0.1 + 0.2, 0.3)` gives `True`

**Good to know**
- Integers are always exact (`2 + 3 == 5` is always `True`)
- The issue only affects decimal (float) numbers

In [ ]:
print(0 * np.nan) # nan
print(np.nan == np.nan) # False
print(np.inf > np.nan) # False, Every comparison involving nan (>, <, ==) returns False
print(np.nan - np.nan) #nan
print(0.3 == 3 * 0.1) # False

In [29]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
print(np.diag([1, 2, 3], k=1))

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


## np.diag()

**What it does**
- Builds a square matrix by placing the given values along a diagonal and filling everything else with zeros
- Syntax: `np.diag(values, k=0)`

**The main diagonal**
- The line of positions from the top-left corner to the bottom-right corner of a matrix

**The `k` parameter (which diagonal to use)**
- `k=0`: main diagonal (default)
- `k>0`: diagonals above the main one (`k=1` is one step above)
- `k<0`: diagonals below the main one (`k=-1` is one step below)

**Matrix size**
- `size = number of values + |k|`
- Example: 3 values with `k=0` gives a 3x3 matrix; 3 values with `k=1` or `k=-1` gives a 4x4 matrix
- Diagonals away from the main one are shorter, so the matrix grows to make room for all the values

**Examples**
```python
np.diag([1, 2, 3])          # 3x3, values on the main diagonal
np.diag([1, 2, 3], k=1)     # 4x4, values one step above the main diagonal
np.diag([1, 2, 3], k=-1)    # 4x4, values one step below the main diagonal
```

**Also good to know**
- If you pass a 2D matrix instead of a list, `np.diag()` does the reverse: it extracts the diagonal values from it

15.You need a 5x5 matrix, and you have 4 values (1, 2, 3, 4). Check it: 4 values + |k| = 5, so |k| must be 1. The values go below the main diagonal, so k is negative.

In [34]:
diagonal_function = np.diag([1,2,3,4], k=-1)
print(diagonal_function)
print(diagonal_function.shape)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
(5, 5)


16.Create an 8x8 matrix and fill it with a checkerboard pattern (alternating 0s and 1s):

In [41]:
checker = np.zeros((8, 8), dtype=int)
checker[::2, 1::2] = 1     # even rows, odd columns
checker[1::2, ::2] = 1     # odd rows, even columns
print(checker)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


17.Create a 5x5 matrix of random values and normalize it, meaning subtract the mean and divide by the standard deviation.

In [43]:
normalize = np.random.random((5,5))
mean = normalize.mean()
std = np.std(normalize)

final_output = (normalize - mean) / std
print(final_output)
print(final_output.mean())    # should be very close to 0
print(final_output.std())     # should be very close to 1

[[-0.64566459 -1.18479771  1.31396208 -0.61326043 -0.63895471]
 [-0.37270728 -0.77865034  2.13154289 -1.35870152  0.70929146]
 [ 0.86692354 -0.60899302  1.70260316 -1.20443846 -1.40454384]
 [ 0.53971817  0.04873842  0.25408752 -1.08287323 -0.61138885]
 [ 0.19644343  0.02701748  1.39337538  1.30392386  0.01734659]]
-1.3392065234540951e-16
1.0


18. Multiply a 5x3 matrix by a 3x2 matrix with real matrix multiplication, not element-wise:

In [45]:
matrix1 = np.random.random((5,3))
matrix2 = np.random.random((3,2))
final = np.matmul(matrix1, matrix2)
print(final)
print(final.shape)

[[0.68742052 1.29547725]
 [0.80278355 0.92880131]
 [0.90755901 1.404518  ]
 [0.86962953 1.11318563]
 [0.22326233 0.4886806 ]]
(5, 2)


19. Given this array:

python
Z = np.arange(11)    # [0, 1, 2, ..., 10]

Turn every element that is strictly between 3 and 8 into its negative, in place (modify Z itself, don't create a new array). The result should be:

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]

In [52]:
Z = np.arange(11)             # array of numbers 0 to 10
print(Z)                      # [ 0  1  2  3  4  5  6  7  8  9 10]

mask = (Z > 3) & (Z < 8)      # yes/no question for each number: bigger than 3 AND smaller than 8
print(mask)                   # True only at the positions of 4, 5, 6, 7

print(Z[mask])                # keeps only the numbers where mask is True: [4 5 6 7]

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True False False False]
[4 5 6 7]


20.Create a random vector of size 10, find its largest value, and replace that value with 0.

## np.argmax() and np.argmin()

**What they do**
- `np.argmax(arr)` returns the **position (index)** of the largest value in an array
- `np.argmin(arr)` returns the **position (index)** of the smallest value in an array
- They give a position, not the value itself

**max vs argmax (value vs position)**
- `arr.max()` gives the largest **value**
- `np.argmax(arr)` gives the **index** where that value sits

**Points to remember**
- Give `argmax` the whole array, not a single value
- If the maximum appears more than once, `argmax` returns the position of the **first** one
- For a 2D array, `argmax` works on the flattened array unless you pass `axis`: `axis=0` gives the position of the maximum in each column, `axis=1` in each row


In [59]:
vector = np.random.random(10)    # 10 lockers, each with a random number
a = np.argmax(vector)            # a = the locker NUMBER (position) that holds the biggest value
vector[a] = 0                    # open that locker and put 0 inside
print(vector)                    # the biggest value is gone, replaced by 0


[0.         0.73780971 0.33551193 0.86378941 0.19947991 0.32881669
 0.1951055  0.27042012 0.14349966 0.48809663]
