In [1]:
kanto = [73, 63, 42]
barito = [89, 76, 56]
sinnoh = [102, 43, 37]

In [5]:
w1 = 0.3
w2 = 0.5
w3 = 0.1

weights = [w1, w2, w3]

In [3]:
def crop_yield(region,weight):
    result = 0
    for x, y in zip(region,weight):
        result += x * y
    return result


In [10]:
crop_yield(kanto,weights)

57.6

In [13]:
crop_yield(barito,weights)

70.3

In [14]:
!pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 822.9 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/12.6 MB 904.3 kB/s eta 0:00:14
   --- ------------------------------------ 1.0/12.6 MB 1.0 MB/s eta 0:00:12
   ---- ----------------------------------- 1.3/12.6 MB 1.1 MB/s eta 0:00:11
   ----- ---------------------------------- 1.8/12.6 MB 1.3 MB/s eta 0:00:09
   ------- -------------------------------- 2.4/12.6 MB 1.5 MB/s eta 0:00:08
   --------- ------------------------------ 2.9/12.6 MB 1.6 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.6 MB 1.8 MB/s eta 0:00:05
   -------------- ------------


[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: C:\Users\balar.CHETAN\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [15]:
import numpy as np  # NumPy: fast array operations for numerical/data computations

Numpy arrays can be created using the np.array function

In [16]:
Kanto = np.array([73, 62, 42])

In [18]:
weights = np.array([w1, w2, w3])

In [20]:
print(Kanto)
print(weights)

[73 62 42]
[0.3 0.5 0.1]


In [21]:
type(Kanto)
type(weights)

numpy.ndarray

In [23]:
Kanto


array([73, 62, 42])

just like lists in python, Numpy array support the indexing notation []

In [25]:
weights[0]
Kanto[2]

42

Operating on Numpy arrays 

we can now compute the dot product of two vectors using np.dot function 

In [26]:
np.dot(Kanto,weights)

57.099999999999994

we can achieve the same result with lower level operations supported buy Numpy arrays:
performing an element-wise multiplication and calculating the sum of the resulting numbers.

In [27]:
kanto


[73, 63, 42]

In [29]:
weights

array([0.3, 0.5, 0.1])

In [31]:
kanto * weights # gives elemet wise multiplication


array([21.9, 31.5,  4.2])

In [32]:
(kanto * weights).sum()

57.6

the * operator is overloaded in NumPy to perform element-wise multiplication. 
When you multiply two NumPy arrays of the same shape, 
it multiplies each corresponding element together.
and the sum() method calculate the sum of numbers in an array


In [33]:
a = np.array([1,2,3])
b = np.array([7,8,9,6])

In [35]:
# a * b # it only works when array are of same size


In [36]:
a.sum()

6

## Benefits of NumPy Arrays

1. **Speed** - much faster than Python lists for numerical operations
2. **Memory Efficient** - uses less memory since all elements are the same type
3. **Vectorized Operations** - apply operations to entire array without loops
4. **Multidimensional Support** - easily handles 2D/3D data like images and tables

In [40]:
# python lists
arr1 = list(range(10000000))
arr2 = list(range(10000000,20000000))

# numpy list
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [41]:
%%time
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

CPU times: total: 2.09 s
Wall time: 2.38 s


833333233333335000000

In [42]:
%%time 
np.dot(arr1_np,arr2_np)

CPU times: total: 15.6 ms
Wall time: 23.4 ms


690258880

As we see np.dot is much faster than python for loop . so numpy is usefull for large dataset.


Multi-dimensional Numpy Arrays 

In [61]:
climate_data = np.array([[76,65,43],[56,89,76],[45,76,89],[111,110,65],[48,59,60]])


In [62]:
climate_data

array([[ 76,  65,  43],
       [ 56,  89,  76],
       [ 45,  76,  89],
       [111, 110,  65],
       [ 48,  59,  60]])

numpy arrays can have any no. of dimensions and different lengths along each dimension. 
we can inspect the length along each dimension using the .shape attribute/property of the array 


In [63]:
climate_data.shape

(5, 3)

In [64]:
weights.shape

(3,)

In [50]:
# 3d array
arr3 = np.array([[[11,12,13],[14,15,16]],[[17,19,20],[23,34,45]]])

In [51]:
arr3.shape

(2, 2, 3)

all the elements in the array must have the same datatype......
you can check the datatype
of the array using .dtype attribute


In [55]:
arr3.dtype


dtype('int32')

In [57]:
arr3.ndim


3

## shape aur ndim

- **shape**: array ke har level pe kitne elements hain, batata hai (jaise `(2,3)` = 2 rows, 3 columns)
- **ndim**: array me kitne dimensions/levels hain, batata hai (jaise 1D, 2D, 3D)

if an array contain an single floating point number, all the other element are also converted to floats 

In [58]:
arr4 = np.array([[[11,12,13.3],[14,15,16]],[[17,19,20],[23,34,45]]])
arr4.dtype

dtype('float64')

In [59]:
arr = np.array([1, 2, 3])
print(arr.dtype)   # int64 (ya int32, system pe depend karta hai)

arr2 = np.array([1.5, 2.5])
print(arr2.dtype)  # float64

arr3 = np.array([1, 2.5])   # mix of int and float
print(arr3.dtype)  # float64 - NumPy automatically upgrade kar deta hai

int32
float64
float64


We can now compute the predicted yields of apples in all the regions,
using a single matrix multiplication between climate_data (a 5x3 matrix) 
and weights (a vector of length 3). Here's what it looks like visually:

In [67]:
c= np.matmul(climate_data,weights) # for matrix multiplication we use this 

In [68]:
c.shape


(5,)

Numpy also provides helper functions reading from & writing to files. Let's download a file climate.txt which contains 10,000 climate data (temperature, rainfall & humidity) in the following format:

temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...

This format of storing data is known as comma separated values or CSV.

CSVs: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)

To read this file into a numpy array, we can use the genfromtxt function.

In [72]:
import urllib.request
urllib.request.urlretrieve(
    'https://raw.githubusercontent.com/the-stranger-web/jovian_Data_Analyst/refs/heads/main/italy-covid-daywise.csv',
    'italy-covid-daywise.csv'
)

('italy-covid-daywise.csv', <http.client.HTTPMessage at 0x1de02c481a0>)

## urllib

- Python ka **built-in library** hai (already installed aati hai)
- Kaam: internet se files/data download karna, URLs ke saath kaam karna

### Example
```python
import urllib.request
urllib.request.urlretrieve('https://example.com/data.csv', 'data.csv')
```
- Isse URL wali file directly computer pe download ho jaati hai

In [74]:
covid_data = np.genfromtxt('italy-covid-daywise.csv', delimiter=',', skip_header=1)
print(covid_data)

[[        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.0000e+00         nan]
 [        nan  0.0000e+00  0.00

## Downloading & Loading a Real CSV Dataset

### Download from URL
```python
import urllib.request
urllib.request.urlretrieve(
    'https://raw.githubusercontent.com/.../italy-covid-daywise.csv',
    'italy-covid-daywise.csv'
)
```
- Internet se file ko local system pe save karta hai

### Load into NumPy array
```python
covid_data = np.genfromtxt('italy-covid-daywise.csv', delimiter=',', skip_header=1)
```
- CSV ko NumPy array me convert karta hai
- `skip_header=1` → column names wali first row skip

### Note
- Real-world CSVs me text columns (jaise dates) hone se error/NaN aa sakta hai — Pandas is case me better hota hai

In [75]:
covid_data.shape

(248, 4)

In [77]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Dono same result denge
result1 = a @ b
result2 = np.matmul(a, b)

print(result1)
print(result2)
# Dono ka output same hoga: [[19, 22], [43, 50]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [79]:
a = np.array([1,2,3])
b = np.array([4,5,6,7,8])
final = np.concatenate((a,b))
final


array([1, 2, 3, 4, 5, 6, 7, 8])

## np.concatenate() — Common Mistake

**Galat:**
```python
np.concatenate(a, b)
```
Error: `TypeError` — arrays tuple ke andar dena zaroori hai

**Sahi:**
```python
np.concatenate((a, b))
```
- Extra bracket `( )` zaroori hai — ye ek **tuple** hai jisme dono arrays hain
- 1D arrays me alag lengths ho sakti hain, koi problem nahi (axis ki zaroorat nahi)

In [80]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.concatenate((a, b), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [81]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [82]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.sum(axis=0))   # Output: [5 7 9]  -> column-wise sum (upar-neeche add)
print(arr.sum(axis=1))   # Output: [6 15]   -> row-wise sum (left-right add)

[5 7 9]
[ 6 15]


## axis Parameter (general rule)
- `axis=0` → rows ki direction (upar-neeche), column-wise operation
- `axis=1` → columns ki direction (left-right), row-wise operation
- Sirf concatenate nahi, sum/mean/etc. me bhi yehi rule chalta hai

In [85]:
## np.reshape()

#**Rule:** Total elements same rehne chahiye, sirf arrangement badalta hai


arr = np.array([1, 2, 3, 4, 5, 6])   # shape: (6,)

arr.reshape(2, 3)
# [[1 2 3]
#  [4 5 6]]

arr.reshape(3, 2)
# [[1 2]
#  [3 4]
#  [5 6]]


#`-1` trick: NumPy khud calculate kar leta hai

arr.reshape(2, -1)   # NumPy khud 3 nikal lega -> shape (2,3)


#Error case: `arr.reshape(2, 4)` → Error, kyunki 2×4=8 ≠ 6 elements

array([[1, 2, 3],
       [4, 5, 6]])

## np.reshape()
- Array ka shape/structure badalta hai, data same rehta hai
- Rule: total elements match hone chahiye (e.g. 6 elements → 2×3 ya 3×2, but not 2×4)
- `-1` trick: NumPy khud calculate kar leta hai wo dimension

## np.savetxt()
- Array ko file me save karta hai (genfromtxt ka opposite)
- Syntax: `np.savetxt('file.txt', arr, delimiter=',', fmt='%d')`
- `fmt` se output format clean kar sakte ho
- MLP me Pandas (`df.to_csv()`) zyada use hoga isi kaam ke liye

Numpy provides hundreds of functions for peforming operations on arrays. Here are some common functions:

Mathematics: np.sum, np.exp, np.round, arithemtic operators
Array manipulation: np.reshape, np.stack, np.concatenate, np.split
Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
Statistics: np.mean, np.median, np.std, np.max

How to find the function you need? Since Numpy offers hundreds of functions for operating on arrays, it can sometimes be hard to find exactly what you need. The easiest way to find the right function is to do a web search e.g. searching for "How to join numpy arrays" leads to this tutorial on array concatenation.

Arithmetic operations and broadcasting

Numpy arrays support arithmetic operators like +, -, * etc. You can perform an arithmetic operation with a single number (also called scalar), or with another array of the same shape. This makes it really easy to write mathemtical expressions with multi-dimensional arrays.

In [86]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [87]:
arr3 = np.array([[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 11, 12, 13]])

In [88]:
arr2+3


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [89]:
final = arr2 + arr3

In [90]:
final


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [91]:
arr3 / 3


array([[3.66666667, 4.        , 4.33333333, 4.66666667],
       [5.        , 5.33333333, 5.66666667, 6.        ],
       [6.33333333, 3.66666667, 4.        , 4.33333333]])

1790346623837_image.png
Numpy arrays also support brodcasting, which allows arthmetic operations between two array having a different number of dimensions, but compatible shapes. Let's look at an example to see how it works.

In [92]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [93]:
arr2.shape


(3, 4)

In [94]:
arr4 = np.array([4,5,6,7])

In [95]:
arr4.shape

(4,)

In [98]:
arr2 + arr4 # just add row in entire matrix (each row)

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression arr2 + arr4 is evaluated, arr4 (which has the shape (4,)) is replicated 3 times to match the shape (3, 4) of arr2. This is pretty useful, because numpy performs the replication without actually creating 3 copies of the smaller dimension array.

In [105]:
arr5 = np.array([7,8])

In [106]:
arr5.shape

(2,)

# arr2 + arr5
1790347253066_image.png
In the above example, even if arr5 is replicated 3 times, it will not match the shape of arr2,
hence arr2 + arr5 cannot be evaluted successfully. 

Numpy arrays also support comparision operations like ==, !=, > etc. The result is an array of booleans.